Update AndroidManifest.tmpl.xml
kivy/python-for-android pull request #2551
Opened 2022-02-05 22:12 UTC by drahba

For the apps targeting api level 31 (A12) and contain activities, services, or broadcast receivers that use intent filters, you must explicitly declare the android:exported attribute for these app components. If an activity, service, or broadcast receiver uses intent filters and doesn't have an explicitly-declared value for android:exported, your app can't be installed on a device that runs Android 12 or higher. (https://developer.android.com/about/versions/12/behavior-changes-12). I added three changes accordingly with the requirements.

2022-02-06 15:12 UTC, misl6 requested changes
Thank you for mixing the PRs as required.
I've left some minor comments. Can you address these issues?

PS: There's no need to open a new PR, feel free to add another commit into this one. I will squash the two ones while merging.

2022-02-06 15:12 UTC, misl6 commented on pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
> +                     android:exported="true"
Can you fix the indentation here?

2022-02-06 15:12 UTC, misl6 commented on pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
> +                     android:exported="true">
Can you fix the indentation here?

2022-02-06 15:12 UTC, misl6 commented on pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
> +                     android:exported="false">
Can you fix the indentation here?

2022-02-06 20:21 UTC, drahba commented on pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
> +                     android:exported="true"
corrected indentation via spacing

2022-02-06 20:21 UTC, drahba commented on pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
> +                     android:exported="true">
corrected indentation via spacing

2022-02-06 20:21 UTC, drahba commented on pythonforandroid/bootstraps/sdl2/build/templates/AndroidManifest.tmpl.xml
> +                     android:exported="false">
corrected indentation via spacing

2022-02-10 17:21 UTC, misl6 approved these changes
LGTM. Thank you!

2022-02-10 17:21 UTC, merged

2022-06-20 18:22 UTC, legeartisgames commented
I applied the latest version of p4a (which was claimed to support Android 12) to build an .aab using buildozer (target api level is 33). When trying to load .aab or .apk files to Play Console, I got error message connected with the problem raising in this issue (about android:exported).
Though, if I figured the discussion out rightly, the result of the outcome of it must include eliminating of the problem I faced. 

Does really exist a flaw in the latest version of p4a, or did I something wrong?
I suppose I did something incorrect, if anybody had successfully uploaded .aab version with api-level more than 30.

2022-06-21 07:42 UTC, drahba commented
> I applied the latest version of p4a (which was claimed to support Android 12) to build an .aab using buildozer (target api level is 33). When trying to load .aab or .apk files to Play Console, I got error message connected with the problem raising in this issue (about android:exported). Though, if I figured the discussion out rightly, the result of the outcome of it must include eliminating of the problem I faced.
> 
> Does really exist a flaw in the latest version of p4a, or did I something wrong? I suppose I did something incorrect, if anybody had successfully uploaded .aab version with api-level more than 30.

if added activities, services, or broadcast receivers that use intent filters to the androidmanifest.xml file, you must declare the android:exported attribute yourself, the current changes take care of the existing intent filters not the ones you added after you build your app.