recipes: new recipe `coincurve`
kivy/python-for-android pull request #2835
Opened 2023-06-06 13:58 UTC by T-Dynamos

Hello!

2023-06-06 16:29 UTC, misl6 requested changes

2023-06-06 16:29 UTC, misl6 commented on pythonforandroid/recipes/coincurve/__init__.py
> +    depends = [('python2', 'python3crystax'), 'setuptools',
Hi @T-Dynamos !

`python2` and `python3crystax` are not in our recipe list anymore.

Can you please update the recipe accordingly?

2024-03-09 19:29 UTC, AndreMiras commented
Hi @T-Dynamos, thanks for the PR, sorry for the delay, the PR got buried under.
Is the recipe still relevant?
If so would you mind rebasing so that it triggers a build.
```
git pull --rebase upstream develop # assuming upstream is the remote name
```

2024-03-10 04:26 UTC, T-Dynamos commented
@AndreMiras Done!.

2024-03-10 08:01 UTC, AndreMiras commented
Awesome job, thanks!

2024-03-10 08:01 UTC, merged